// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idhtutcjkniszcsoyyrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkaHR1dGNqa25pc3pjc295eXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MjM2MjcsImV4cCI6MjA2MTQ5OTYyN30.7DvUoP1Cdfhed6iynfrtA4_4GhvjEypae28XqORdhn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);